### ISSUE TITLE
pyribs API changing

### ISSUE THREAD

**Issue by btjanaka** [morgangiraud/leniax#33]
Hi @morgangiraud! I see that your project depends on pyribs>=0.4.0. I wanted to let you know that we will be releasing pyribs 0.5.0 in a few weeks, which will have a very different API than pyribs 0.4.0. To avoid breaking your library, I suggest pinning pyribs to 0.4.0 in your setup.py file or upgrading as necessary. Thank you!

**Comment by morgangiraud** [comment]
Hi @btjanaka Thanks a lot for reaching out about this! I've just updated the `setup.py` file. 

Can you please ping me here when you release it? 
I'm really curious about it!

**Comment by btjanaka** [comment]
Hi @morgangiraud! I'm excited to announce that pyribs v0.5.0 is now available. See our Twitter thread for more info: https://twitter.com/btjanaka/status/1628500413938028544
